package TikkeulMountainApp.party;

public class ASCII {

    public static void printTikkeulMountain() throws InterruptedException {
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("          ___");
        System.out.println("         /    \\");
        System.out.println("        /      \\");
        System.out.println("       /        \\");
        System.out.println("       ㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("              ____");
        System.out.println("            /      \\");
        System.out.println("           /        \\");
        System.out.println("          /          \\");
        System.out.println("         /            \\");
        System.out.println("        ㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("              ____");
        System.out.println("            /      \\");
        System.out.println("           /        \\");
        System.out.println("          /          \\");
        System.out.println("         /            \\");
        System.out.println("        /              \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();

        System.out.println("              ________");
        System.out.println("             /        \\");
        System.out.println("            /          \\");
        System.out.println("           /            \\");
        System.out.println("          /              \\");
        System.out.println("         /                \\");
        System.out.println("        /                  \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("               ________");
        System.out.println("              /        \\");
        System.out.println("             /          \\");
        System.out.println("            /            \\");
        System.out.println("           /              \\");
        System.out.println("          /                \\");
        System.out.println("         /                  \\");
        System.out.println("        /                    \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                ________");
        System.out.println("               /        \\");
        System.out.println("              /          \\");
        System.out.println("             /            \\");
        System.out.println("            /              \\");
        System.out.println("           /                \\");
        System.out.println("          /                  \\");
        System.out.println("         /                    \\");
        System.out.println("        /                      \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                __________");
        System.out.println("               /          \\");
        System.out.println("              /            \\");
        System.out.println("             /              \\");
        System.out.println("            /                \\");
        System.out.println("           /                  \\");
        System.out.println("          /                    \\");
        System.out.println("         /                      \\");
        System.out.println("        /                        \\");
        System.out.println("       /                          \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                ____________");
        System.out.println("               /            \\");
        System.out.println("              /              \\");
        System.out.println("             /                \\");
        System.out.println("            /                  \\");
        System.out.println("           /                    \\");
        System.out.println("          /                      \\");
        System.out.println("         /                        \\");
        System.out.println("        /                          \\");
        System.out.println("       /                            \\");
        System.out.println("      /                              \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                ____________");
        System.out.println("               /            \\");
        System.out.println("              /              \\");
        System.out.println("             /                \\");
        System.out.println("            /                  \\");
        System.out.println("           /                    \\");
        System.out.println("          /                      \\");
        System.out.println("         /                        \\");
        System.out.println("        /                          \\");
        System.out.println("       /                            \\");
        System.out.println("      /                              \\");
        System.out.println("     /                                \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(10);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                ______________");
        System.out.println("               /              \\");
        System.out.println("              /                \\");
        System.out.println("                 /                  \\");
        System.out.println("                /                    \\");
        System.out.println("               /                      \\");
        System.out.println("              /                        \\");
        System.out.println("             /                          \\");
        System.out.println("            /                            \\");
        System.out.println("           /                              \\");
        System.out.println("          /                                \\");
        System.out.println("         /                                  \\");
        System.out.println("        /                                    \\");
        System.out.println("       /                                      \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                ________________");
        System.out.println("               /                \\");
        System.out.println("              /                  \\");
        System.out.println("             /                    \\");
        System.out.println("            /                      \\");
        System.out.println("           /                        \\");
        System.out.println("          /                          \\");
        System.out.println("         /                            \\");
        System.out.println("        /                              \\");
        System.out.println("       /                                \\");
        System.out.println("      /                                  \\");
        System.out.println("     /                                    \\");
        System.out.println("    /                                      \\");
        System.out.println("   /                                        \\");
        System.out.println("  /                                          \\");
        System.out.println(" /                                            \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                ________________");
        System.out.println("               /                \\");
        System.out.println("              /                  \\");
        System.out.println("             /                    \\");
        System.out.println("            /                      \\");
        System.out.println("           /                        \\");
        System.out.println("          /                          \\");
        System.out.println("         /                            \\");
        System.out.println("        /                              \\");
        System.out.println("       /                                \\");
        System.out.println("      /                                  \\");
        System.out.println("     /                                    \\");
        System.out.println("    /                                      \\");
        System.out.println("   /                                        \\");
        System.out.println("  /                                          \\");
        System.out.println(" /                                            \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                                   _");
        System.out.println("                                                /    \\");
        System.out.println("                              /        \\");
        System.out.println("                                                  /            \\");
        System.out.println("                                ___       /                \\        ___");
        System.out.println("                              /        \\    /                    \\    /        \\");
        System.out.println("                            /            \\/                        \\/            \\");
        System.out.println("                          /              /                        \\              \\");
        System.out.println("                        /              /                                \\              \\");
        System.out.println("                      /                                                                    \\");
        System.out.println("                    /                                                                        \\");
        System.out.println("                  /                                                                            \\");
        System.out.println("                /                                                                                \\");
        System.out.println("              /                                                                                    \\");
        System.out.println("            /                                                                                        \\");
        System.out.println("          /                                                                                            \\");
        System.out.println("        /                                                                                                \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                                      _");
        System.out.println("                                    /     \\");
        System.out.println("                                   /        \\");
        System.out.println("                                                /            \\");
        System.out.println("                              /                \\");
        System.out.println("                                 __           /                    \\             __");
        System.out.println("                               /     \\        /                        \\        /      \\");
        System.out.println("                             /         \\    /                            \\    /          \\");
        System.out.println("                            /            \\/                                \\/              \\");
        System.out.println("                          /              /                                \\                \\");
        System.out.println("                        /              /                                        \\                \\");
        System.out.println("                      /                                                                              \\");
        System.out.println("                    /                                                                                      \\");
        System.out.println("                  /                                                                                          \\");
        System.out.println("                /                                                                                              \\");
        System.out.println("              /                                                                                                  \\");
        System.out.println("            /                                                                                                      \\");
        System.out.println("          /                                                                                                          \\");
        System.out.println("        /                                                                                                              \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                             /\\");
        System.out.println("                            /   \\");
        System.out.println("                           /     \\");
        System.out.println("                          /       \\");
        System.out.println("                         /         \\");
        System.out.println("                        /           \\");
        System.out.println("                       /             \\");
        System.out.println("                      /               \\        /\\");
        System.out.println("                     /                 \\      /     \\             /    \\");
        System.out.println("                    /                   \\    /                                  \\         /        \\");
        System.out.println("                   /                     \\  /                                    \\     /            \\");
        System.out.println("                  /                         /                                           \\ /              \\");
        System.out.println("                 /                         /                                               \\                \\");
        System.out.println("                /                                                                                    \\");
        System.out.println("               /                                                                                         \\");
        System.out.println("              /                                                                                             \\");
        System.out.println("             /                                                                                                 \\");
        System.out.println("            /                                                                                                     \\");
        System.out.println("           /                                                                                                         \\");
        System.out.println("          /                                                                                                             \\");
        System.out.println("         /                                                                                                                 \\");
        System.out.println("        /                                            \\");
        System.out.println("       /                                                       \\");
        System.out.println("       ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");

        Thread.sleep(100); // 0.2초 (200 밀리초) 대기

    }
}
