package TikkeulMountainApp.party;

public class ASCII {

    public static void printTikkeulMountain() throws InterruptedException {
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("    ____");
        System.out.println("   /    \\");
        System.out.println("  /      \\");
        System.out.println("  ㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("     ___");
        System.out.println("    /   \\");
        System.out.println("   /     \\");
        System.out.println("  /       \\                                          0  o  ");
        System.out.println("  ㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("        ____");
        System.out.println("      /      \\");
        System.out.println("     /        \\");
        System.out.println("    /          \\");
        System.out.println("   /            \\                     0  o  O............. ");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("         ____");
        System.out.println("       /      \\");
        System.out.println("      /        \\");
        System.out.println("     /          \\");
        System.out.println("    /            \\");
        System.out.println("   /              \\            0  o  O  o  O  o  ㅇ ......... ");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("          ________");
        System.out.println("        /         \\");
        System.out.println("       /           \\");
        System.out.println("      /             \\");
        System.out.println("     /               \\");
        System.out.println("    /                 \\");
        System.out.println("   /             0   ㅇ\\ o  ㅇ  o  0  ㅇ  0 o  ㅇ o ㅇ o o.....");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("         ________");
        System.out.println("        /        \\");
        System.out.println("       /          \\");
        System.out.println("      /    0       \\");
        System.out.println("     /         ㅇ   \\");
        System.out.println("    /   o     0      \\");
        System.out.println("   /       ㅇ         \\");
        System.out.println("  /            ㅇ   0  \\o  ㅇ  o  0  ㅇ  0 o  ㅇ o ㅇ o o.....");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("          ________");
        System.out.println("         /        \\");
        System.out.println("        / 0      ㅇ\\");
        System.out.println("       /             \\");
        System.out.println("      /     ㅇ     0  \\");
        System.out.println("     /                 \\");
        System.out.println("    /     ㅇ     0      \\");
        System.out.println("   /                 ㅇ  \\");
        System.out.println("  /     0                 \\o  ㅇ  o  0  ㅇ  0 o  ㅇ o ㅇ o o...");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("           __________");
        System.out.println("          /  ㅇ      \\");
        System.out.println("         /  O     O   \\");
        System.out.println("        /     0    ㅇ  \\");
        System.out.println("       /  O    O    0   \\");
        System.out.println("      /    ㅇ       O    \\");
        System.out.println("     /  0    O   0     0  \\");
        System.out.println("    /      0   O   0   ㅇ  \\");
        System.out.println("   /   0    O    O    O     \\");
        System.out.println("  /      ㅇ   O    0    0    \\o  0 o  0  ㅇ  0 o  ㅇ o ㅇ o o....");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("            ____________");
        System.out.println("           /  o    o     \\");
        System.out.println("          /    0     O    \\");
        System.out.println("         / o    O   o    o \\");
        System.out.println("        /    O  o     O     \\");
        System.out.println("       /  O   0     o     0  \\");
        System.out.println("      /    o     O   o        \\");
        System.out.println("     / o    O  o    O    o    O\\");
        System.out.println("    /    O      o   o   O    O  \\");
        System.out.println("   /   o      O   0    o   o     \\");
        System.out.println("  /     o  o     O      o       O \\o   o  0  ㅇ  0 o  ㅇ o ㅇ o o..");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("             ____________");
        System.out.println("            /  ㅇ        \\");
        System.out.println("           / o      o  0  \\");
        System.out.println("          /    ㅇ          \\");
        System.out.println("         /   o   o   ㅇ  ㅇ \\");
        System.out.println("        /    0       o       \\");
        System.out.println("       /  0   ㅇ   o  ㅇ  ㅇ  \\");
        System.out.println("      /    o       ㅇ    o     \\");
        System.out.println("     /      ㅇ          ㅇ      \\");
        System.out.println("    /     o        o       0     \\");
        System.out.println("   /   ㅇ       ㅇ                \\");
        System.out.println("  /     0     o       o   ㅇ    ㅇ \\o   o  0  ㅇ  0 o  ㅇ o ㅇ...");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(10);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("               ________________");
        System.out.println("              /     o     ㅇ   \\");
        System.out.println("             /   0  o  o     o  \\");
        System.out.println("            /   o   o    ㅇ     o\\");
        System.out.println("           /     o    o    0    o \\");
        System.out.println("          /     0    o   o       ㅇ\\");
        System.out.println("         /   o     o       o        \\");
        System.out.println("        /      o    ㅇ      0   o    \\");
        System.out.println("       /     ㅇ     o        o   o    \\");
        System.out.println("      /    o   o      ㅇ    o        0 \\");
        System.out.println("     /  o    0   o              ㅇ      \\");
        System.out.println("    /       o     0   o       o     o    \\");
        System.out.println("   /    ㅇ        o      o    ㅇ         0\\o    0  ㅇ  0 o  ㅇ o.. ");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                ______________");
        System.out.println("               /      ㅇ      \\");
        System.out.println("              /    O    o  O ㅇ\\");
        System.out.println("             / o   0     0    o \\");
        System.out.println("            /     O   o    o   ㅇ\\");
        System.out.println("           /  o    ㅇ    O        \\");
        System.out.println("          /              0   0   o \\");
        System.out.println("         / o  O    0    O   ㅇ      \\");
        System.out.println("        /                o    O      \\");
        System.out.println("       /   o    ㅇO            o    0 \\");
        System.out.println("      /    O            ㅇ             \\");
        System.out.println("     /     O    o    O       O     o    \\");
        System.out.println("    /     0         0 o       ㅇ   O   0 \\");
        System.out.println("   /         ㅇ         O     ㅇ          \\ㅇ  0 o  ㅇ o  ㅇ...");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("               ______________");
        System.out.println("              /  o    ㅇ   O \\");
        System.out.println("             /  o     O    ㅇ \\");
        System.out.println("            /    0     0   O   \\");
        System.out.println("           / o       o          \\");
        System.out.println("          /   O  ㅇ        o     \\");
        System.out.println("         /         o    0    O    \\");
        System.out.println("        /   o           O   o     0\\");
        System.out.println("       /    O  o  0        O     ㅇ \\");
        System.out.println("      /          o      ㅇ           \\");
        System.out.println("     /    O  ㅇ            O      ㅇ  \\");
        System.out.println("    /   ㅇ      o   O     oo   O     0 \\");
        System.out.println("   /     ㅇ    0    O     ㅇ            \\");
        System.out.println("  /  0    o        o      0     o    ㅇ  \\ㅇ ㅇ  0 o  ㅇ o 0....");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                 ______________");
        System.out.println("                /     o   O     \\");
        System.out.println("               /   0     ㅇ  o   \\");
        System.out.println("              /       O  O        \\");
        System.out.println("             /    ㅇ       ㅇ   o  \\");
        System.out.println("            /      O   0    ㅇ      \\");
        System.out.println("           /    O           o  o     \\");
        System.out.println("          /       ㅇ   o    Oㅇ    0  \\");
        System.out.println("         /   0  ㅇ                     \\");
        System.out.println("        /    O       o     0      ㅇ    \\");
        System.out.println("       /  O     ㅇ       ㅇ      O    ㅇ \\");
        System.out.println("      /     o       O  o                  \\");
        System.out.println("     /    ㅇ  0     O   o  ㅇ      0  o    \\");
        System.out.println("    /     ㅇ    o        O        O       0 \\");
        System.out.println("   / O        O       0      O          ㅇ   \\ ㅇ  0 ㅇ   o  O  O o ");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                  _______________");
        System.out.println("                 /    o    ㅇ     \\");
        System.out.println("                / 0       o      O \\");
        System.out.println("               /      ㅇ    O    0  \\");
        System.out.println("              /           ㅇ     ㅇ  \\");
        System.out.println("             /     0       o        O \\");
        System.out.println("            /           ㅇ        0   O\\");
        System.out.println("           /    0                ㅇ     \\");
        System.out.println("          /             ㅇ   0        0  \\");
        System.out.println("         /  o      0               o     O\\");
        System.out.println("        /     ㅇ           ㅇ  o    ㅇ   o \\");
        System.out.println("       /           O      0         00   O  \\");
        System.out.println("      /   0        ㅇ            o           \\");
        System.out.println("     /  O     O         o    0   ㅇ   O  ㅇ   \\");
        System.out.println("    /     ㅇ    0 ㅇ               O         0 \\");
        System.out.println("   /   ㅇ     O        0       o     0      o   \\ㅇ  0 ㅇ 0 o  O ");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                  _______________");
        System.out.println("                 /    ㅇ         \\");
        System.out.println("                /   ㅇ    O    o  \\");
        System.out.println("               /           0       \\");
        System.out.println("              /     O          ㅇ   \\");
        System.out.println("             /     0   ㅇ         o  \\");
        System.out.println("            /            0    O    0  \\");
        System.out.println("           /      o                 ㅇ \\");
        System.out.println("          /      O   ㅇ         o       \\");
        System.out.println("         /    0       O   O    ㅇ    O   \\");
        System.out.println("        /         ㅇ              0       \\");
        System.out.println("       /    O       o      0          O    \\");
        System.out.println("      /      o    ㅇ     o      o       ㅇ  \\");
        System.out.println("     /   o   0             0      O   ㅇ     \\");
        System.out.println("    /          0      ㅇ                   0  \\");
        System.out.println("   /  0    O                   0       O       \\");
        System.out.println("  /           ㅇ        O           o       ㅇ  \\ㅇ  0 ㅇ 0 o  O ");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                                 __________");
        System.out.println("                                /          \\");
        System.out.println("                               /            \\");
        System.out.println("                              /              \\");
        System.out.println("                             /                \\");
        System.out.println("                            /                  \\ ");
        System.out.println("               _________   /                    \\  ________");
        System.out.println("              /         \\/                      \\/        \\");
        System.out.println("             /                                               \\");
        System.out.println("            /                                                 \\");
        System.out.println("           /                                                   \\");
        System.out.println("          /                                                     \\");
        System.out.println("         /                                                       \\");
        System.out.println("        /                                                         \\");
        System.out.println("       /                                                           \\");
        System.out.println("      /                                                             \\");
        System.out.println("     /                                                               \\");
        System.out.println("    /                                                                 \\");
        System.out.println("   /                                                                   \\");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                                   ______");
        System.out.println("                                 /        \\");
        System.out.println("                                /          \\");
        System.out.println("                               /            \\");
        System.out.println("                              /              \\");
        System.out.println("                             /                \\ ");
        System.out.println("                _______     /                  \\    ______");
        System.out.println("               /       \\  /                    \\  /      \\");
        System.out.println("              /         \\/                      \\/        \\");
        System.out.println("             /                                               \\");
        System.out.println("            /                                                 \\");
        System.out.println("           /                                                   \\");
        System.out.println("          /                                                     \\");
        System.out.println("         /                                                       \\");
        System.out.println("        /                                                         \\");
        System.out.println("       /                                                           \\");
        System.out.println("      /                                                             \\");
        System.out.println("     /                                                               \\");
        System.out.println("    /                                                                 \\");
        System.out.println("   /                                                                   \\");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                                   ____");
        System.out.println("                                  /    \\");
        System.out.println("                                 /      \\");
        System.out.println("                                /        \\");
        System.out.println("                               /          \\");
        System.out.println("                              /            \\");
        System.out.println("                             /              \\ ");
        System.out.println("                _____       /                \\      ____");
        System.out.println("               /     \\    /                  \\    /    \\");
        System.out.println("              /       \\  /                    \\  /      \\");
        System.out.println("             /         \\/                      \\/        \\");
        System.out.println("            /                                               \\");
        System.out.println("           /                                                 \\");
        System.out.println("          /                                                   \\");
        System.out.println("         /                                                     \\");
        System.out.println("        /                                                       \\");
        System.out.println("       /                                                         \\");
        System.out.println("      /                                                           \\");
        System.out.println("     /                                                             \\");
        System.out.println("    /                                                               \\");
        System.out.println("   /                                                                 \\");
        System.out.println("  /                                                                   \\");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                                     __");
        System.out.println("                                    /  \\");
        System.out.println("                                   /    \\");
        System.out.println("                                  /      \\");
        System.out.println("                                 /        \\");
        System.out.println("                                /          \\");
        System.out.println("                               /            \\");
        System.out.println("                   __         /              \\        __ ");
        System.out.println("                 /   \\      /                \\      /  \\");
        System.out.println("                /     \\    /                  \\    /    \\");
        System.out.println("               /       \\  /                    \\  /      \\");
        System.out.println("              /         \\/                      \\/        \\");
        System.out.println("             /                                               \\");
        System.out.println("            /                                                 \\");
        System.out.println("           /                                                   \\");
        System.out.println("          /                                                     \\");
        System.out.println("         /                                                       \\");
        System.out.println("        /                                                         \\");
        System.out.println("       /                                                           \\");
        System.out.println("      /                                                             \\");
        System.out.println("     /                                                               \\");
        System.out.println("    /                                                                 \\");
        System.out.println("   /                                                                   \\");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");
        Thread.sleep(100);
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("                                    /\\");
        System.out.println("                                   /  \\");
        System.out.println("                                  /    \\");
        System.out.println("                                 /      \\");
        System.out.println("                                /        \\");
        System.out.println("                               /          \\");
        System.out.println("                              /            \\");
        System.out.println("                 / \\        /              \\        /\\ ");
        System.out.println("                /   \\      /                \\      /  \\");
        System.out.println("               /     \\    /                  \\    /    \\");
        System.out.println("              /       \\  /                    \\  /      \\");
        System.out.println("             /         \\/                      \\/        \\");
        System.out.println("            /                                             \\");
        System.out.println("           /                                               \\");
        System.out.println("          /                                                 \\");
        System.out.println("         /                                                   \\");
        System.out.println("        /                                                     \\");
        System.out.println("       /                                                       \\");
        System.out.println("      /                                                         \\");
        System.out.println("     /                                                           \\");
        System.out.println("    /                                                             \\");
        System.out.println("   /                                                               \\");
        System.out.println("  /                                                                 \\");
        System.out.println("  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ");

    }
}
